# Generated by Django 4.2.7 on 2025-04-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_characteristics_battery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id_hub', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hub',
                'verbose_name_plural': 'Hubs',
                'db_table': 'hub',
            },
        ),
        migrations.CreateModel(
            name='PanelData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_panel', models.CharField(max_length=50)),
                ('id_hub', models.CharField(max_length=50)),
                ('generated_power', models.FloatField()),
                ('consumed_power', models.FloatField()),
                ('vertical_position', models.FloatField()),
                ('horizontal_position', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], db_column='status', default='on', max_length=3)),
                ('battery_charge', models.FloatField(db_column='battery_charge')),
            ],
            options={
                'verbose_name': 'Panel Data',
                'verbose_name_plural': 'Panel Data Records',
                'db_table': 'panel_data',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_panel', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('static', 'Static'), ('rotary', 'Rotary')], db_column='type', default='static', max_length=6)),
                ('hub', models.ForeignKey(db_column='id_hub', on_delete=django.db.models.deletion.RESTRICT, to='main.hub')),
            ],
            options={
                'verbose_name': 'Panel',
                'verbose_name_plural': 'Panels',
                'db_table': 'id_panel',
                'unique_together': {('id_panel', 'hub')},
            },
        ),
    ]
