# Generated by Django 4.2.7 on 2025-04-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hub_paneldata_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='coordinates',
            field=models.CharField(blank=True, null=True),
        ),
    ]
