# Generated by Django 4.2.7 on 2025-04-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_panel_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPanelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_panel', models.CharField(max_length=50)),
                ('id_hub', models.CharField(max_length=50)),
                ('generated_power', models.FloatField(blank=True, null=True)),
                ('consumed_power', models.FloatField(blank=True, null=True)),
                ('vertical_position', models.FloatField(blank=True, null=True)),
                ('horizontal_position', models.FloatField(blank=True, null=True)),
                ('last_data_date', models.DateField(blank=True, null=True)),
                ('last_data_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=3, null=True)),
                ('battery_charge', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Latest Panel Data',
                'verbose_name_plural': 'Latest Panel Data',
                'unique_together': {('id_panel', 'id_hub')},
            },
        ),
    ]
