# Generated by Django 4.2.7 on 2025-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_latestpaneldata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paneldata',
            constraint=models.UniqueConstraint(fields=('id_panel', 'id_hub', 'date', 'time'), name='uniq_panel_hub_datetime'),
        ),
    ]
