# Generated by Django 4.2.7 on 2025-05-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_paneldata_uniq_panel_hub_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paneldata',
            name='uniq_panel_hub_datetime',
        ),
    ]
