# Generated by Django 4.2.7 on 2025-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_paneldata_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paneldata',
            name='uniq_panel_hub_datetime',
        ),
        migrations.AddConstraint(
            model_name='paneldata',
            constraint=models.UniqueConstraint(fields=('id_panel', 'id_hub'), name='uniq_panel_hub_datetime'),
        ),
    ]
