# Generated by Django 4.2.7 on 2025-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_paneldata_uniq_panel_hub_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paneldata',
            name='uniq_panel_hub_datetime',
        ),
        migrations.AddConstraint(
            model_name='paneldata',
            constraint=models.UniqueConstraint(fields=('id_panel', 'id_hub', 'date', 'time'), name='uniq_panel_hub_datetime'),
        ),
    ]
